name: Deploy to Tencent Cloud Server

on:
  push:
    branches:
      - main  # Or your default branch, e.g., master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/xphotos # Change this to the path where you cloned your repo on the server
            git pull origin main
            echo "\n>> Building and deploying services..."
            docker-compose up -d --build
            echo "\n>> Cleaning up old docker images..."
            docker image prune -f
